import pptxgen from 'pptxgenjs';
const pptx = new pptxgen();
pptx.layout = 'LAYOUT_WIDE';
pptx.author = 'AI Assistant';
pptx.title = 'AI Agents';
pptx.subject = 'Overview of AI agents';
pptx.company = 'OpenAI';
pptx.lang = 'en-US';
const C = { bg:'0B1020', panel:'111A33', text:'F4F7FB', muted:'B7C3E1', accent:'7C5CFF', accent2:'2EE6A6', gold:'F7C948' };
function addBg(slide, dark=true){ slide.background = { color: dark ? C.bg : 'F7F9FC' }; }
function title(slide, t, s){ slide.addText(t,{x:0.55,y:0.35,w:9.2,h:0.5,fontFace:'Aptos Display',fontSize:28,bold:true,color:C.text,margin:0}); if(s) slide.addText(s,{x:0.55,y:0.82,w:9.2,h:0.35,fontSize:11,color:C.muted,margin:0}); }
let s = pptx.addSlide(); addBg(s,true);
s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:13.333,h:7.5,fill:{color:C.bg},line:{color:C.bg}});
s.addShape(pptx.ShapeType.rect,{x:0.6,y:1.2,w:5.8,h:4.8,fill:{color:C.panel},line:{color:C.panel}});
s.addText('AI Agents',{x:0.9,y:1.65,w:5,h:0.6,fontSize:34,bold:true,color:C.text,margin:0});
s.addText('Autonomous software that perceives, plans, uses tools, and acts toward goals.',{x:0.9,y:2.35,w:4.9,h:0.8,fontSize:16,color:C.muted,margin:0});
s.addShape(pptx.ShapeType.roundRect,{x:7.2,y:1.35,w:5.2,h:4.4,fill:{color:'1A2447'},line:{color:'2A3766',width:1}});
s.addText('Core loop',{x:7.55,y:1.65,w:2,h:0.3,fontSize:14,bold:true,color:C.gold,margin:0});
s.addText('1. Observe\n2. Reason\n3. Use tools\n4. Act\n5. Learn',{x:7.55,y:2.05,w:2.2,h:2.2,fontSize:20,bold:true,color:C.text,margin:0});
s.addText('Examples: customer support bots, coding assistants, research copilots, workflow automations.',{x:7.55,y:4.55,w:4.2,h:0.8,fontSize:12,color:C.muted,margin:0});
s = pptx.addSlide(); addBg(s,false); title(s,'What makes an agent different?','Agents do more than generate text — they decide and execute.');
[['Chatbot','Responds to prompts','No persistent goal or tool use'],['Copilot','Assists a human','Human stays in control'],['Agent','Pursues a goal','Plans, calls tools, and iterates']].forEach((a,i)=>{const x=[0.6,4.72,8.84][i]; s.addShape(pptx.ShapeType.rect,{x:x,y:1.35,w:3.9,h:4.9,fill:{color:'FFFFFF'},line:{color:'D9E2F2',width:1}}); s.addText(a[0],{x:x+0.25,y:1.65,w:3.2,h:0.3,fontSize:18,bold:true,color:'111827',margin:0}); s.addText(a[1],{x:x+0.25,y:2.15,w:3.2,h:0.5,fontSize:14,bold:true,color:C.accent,margin:0}); s.addText(a[2],{x:x+0.25,y:2.85,w:3.2,h:0.8,fontSize:12,color:'374151',margin:0}); s.addShape(pptx.ShapeType.ellipse,{x:x+1.25,y:4.1,w:1.4,h:1.4,fill:{color:i===2?C.accent2:'E5E7EB'},line:{color:i===2?C.accent2:'E5E7EB'}}); s.addText(i===2?'✓':'→',{x:x+1.25,y:4.35,w:1.4,h:0.6,fontSize:28,bold:true,align:'center',color:i===2?'FFFFFF':'6B7280',margin:0});});
s = pptx.addSlide(); addBg(s,false); title(s,'How an AI agent works','A simple architecture for planning and action.');
[['Goal','User intent or task'],['Planner','Breaks work into steps'],['Tools','Search, code, APIs'],['Memory','Stores context'],['Executor','Carries out actions']].forEach((st,i)=>{const x=0.7+i*2.45; s.addShape(pptx.ShapeType.roundRect,{x:x,y:1.8,w:2.1,h:2.2,fill:{color:i%2===0?'FFFFFF':'F3F6FF'},line:{color:'D7E0F2',width:1}}); s.addShape(pptx.ShapeType.ellipse,{x:x+0.65,y:2.0,w:0.8,h:0.8,fill:{color:i===0?C.accent:i===4?C.accent2:'CBD5E1'},line:{color:'FFFFFF',width:1}}); s.addText(String(i+1),{x:x+0.65,y:2.18,w:0.8,h:0.3,fontSize:16,bold:true,align:'center',color:'FFFFFF',margin:0}); s.addText(st[0],{x:x+0.15,y:2.95,w:1.8,h:0.25,fontSize:14,bold:true,align:'center',color:'111827',margin:0}); s.addText(st[1],{x:x+0.15,y:3.25,w:1.8,h:0.55,fontSize:10.5,align:'center',color:'4B5563',margin:0}); if(i<4) s.addText('→',{x:x+2.08,y:2.55,w:0.3,h:0.3,fontSize:22,bold:true,color:C.muted,margin:0});});
s = pptx.addSlide(); addBg(s,true); title(s,'Benefits and risks','Agents unlock speed — but need guardrails.');
s.addShape(pptx.ShapeType.rect,{x:0.7,y:1.35,w:5.8,h:4.9,fill:{color:'121B35'},line:{color:'2A3766',width:1}});
s.addShape(pptx.ShapeType.rect,{x:6.85,y:1.35,w:5.8,h:4.9,fill:{color:'121B35'},line:{color:'2A3766',width:1}});
s.addText('Benefits',{x:1.0,y:1.65,w:2,h:0.3,fontSize:18,bold:true,color:C.accent2,margin:0});
s.addText('• Automate repetitive work\n• 24/7 operation\n• Faster research and triage\n• Personalized assistance',{x:1.0,y:2.1,w:4.8,h:2.2,fontSize:15,color:C.text,margin:0});
s.addText('Risks',{x:7.15,y:1.65,w:2,h:0.3,fontSize:18,bold:true,color:'FF8A80',margin:0});
s.addText('• Hallucinations\n• Tool misuse\n• Data leakage\n• Cost and latency',{x:7.15,y:2.1,w:4.8,h:2.2,fontSize:15,color:C.text,margin:0});
s.addText('Best practice: keep humans in the loop for high-stakes decisions.',{x:0.9,y:5.55,w:11.5,h:0.35,fontSize:12,color:C.muted,align:'center',margin:0});
s = pptx.addSlide(); addBg(s,false); title(s,'Where agents are headed','The next wave is multi-agent systems and better orchestration.');
s.addShape(pptx.ShapeType.rect,{x:0.8,y:1.5,w:11.7,h:3.9,fill:{color:'FFFFFF'},line:{color:'D9E2F2',width:1}});
[['Specialized agents','One agent handles research, another writes, another verifies.'],['Orchestration','A controller routes tasks and checks outputs.'],['Enterprise integration','Agents connect to CRM, docs, code, and data systems.']].forEach((it,i)=>{const x=1.2+i*3.75; s.addShape(pptx.ShapeType.ellipse,{x:x,y:2.0,w:0.7,h:0.7,fill:{color:[C.accent,C.accent2,C.gold][i]},line:{color:'FFFFFF',width:1}}); s.addText(String(i+1),{x:x,y:2.18,w:0.7,h:0.25,fontSize:14,bold:true,align:'center',color:'FFFFFF',margin:0}); s.addText(it[0],{x:x+0.9,y:1.95,w:2.4,h:0.3,fontSize:15,bold:true,color:'111827',margin:0}); s.addText(it[1],{x:x+0.9,y:2.35,w:2.4,h:0.8,fontSize:11.5,color:'4B5563',margin:0});});
s.addText('AI agents are moving from demos to dependable digital coworkers.',{x:1.0,y:5.75,w:11.3,h:0.3,fontSize:14,bold:true,color:C.text,align:'center',margin:0});
await pptx.writeFile({ fileName: 'ai_agents_presentation.pptx' });
